name: macos

on: [push, pull_request]

jobs:

  macos-build:
    runs-on: ${{ matrix.os.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {arch: clang_64, os: macos-13}
          - {arch: arm64, os: macos-latest}

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update
          brew install mosquitto zeromq
        shell: pwsh

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: '${{ github.workspace }}/qt_installation/'
          key: ${{ runner.os }}-QtCache-${{ matrix.os.arch }}-5.15.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.0
        with:
          version: '5.15.2'
          host: 'mac'
          dir: '${{ github.workspace }}/qt_installation/'
          arch: ${{ matrix.os.arch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build Plotjuggler
        shell: pwsh
        run: |
          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler
          cmake --build build --target install