name: macos

on: [push, pull_request]

jobs:
  macos-build:
    runs-on: ${{ matrix.os.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {arch: clang_64, os: macos-13}
          - {arch: arm64, os: macos-latest}

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update
          brew install mosquitto zeromq qt@5
        shell: pwsh

      - name: Build Plotjuggler
        shell: pwsh
        run: |
          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler
          cmake --build build --target install

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3